# Generated by Django 2.2 on 2021-03-31 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20210330_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo_um',
            old_name='denominador',
            new_name='um_equivalencia',
        ),
        migrations.RenameField(
            model_name='grupo_um',
            old_name='numerador',
            new_name='um_origen',
        ),
        migrations.RenameField(
            model_name='grupo_um',
            old_name='denominador_um',
            new_name='unidad_medida',
        ),
        migrations.RemoveField(
            model_name='grupo_um',
            name='numerador_um',
        ),
    ]
