# Generated by Django 2.2 on 2021-04-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_consumo_inv_doc_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo_inv',
            name='multiplicador',
            field=models.FloatField(),
            preserve_default=False,
        ),
    ]
