# Generated by Django 2.2 on 2021-01-11 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_auto_20201104_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'permissions': [('admin_system', 'Permite la visualizacion de la parte administrativa en menu')]},
        ),
    ]
