# Generated by Django 2.2 on 2022-01-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajas', '0002_egresos_detalle_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresos',
            name='hist',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingresos',
            name='hist',
            field=models.TextField(blank=True, null=True),
        ),
    ]
