# Generated by Django 2.2 on 2020-11-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_categoria',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
