# Generated by Django 2.2 on 2021-02-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0003_auto_20210114_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='sub_categoria',
            field=models.TextField(blank=True, null=True),
        ),
    ]
